"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { AnimatePresence, motion } from "framer-motion";
import Transition from "./Components/Transition";
import { useRouter } from "next/navigation";
import Header from "./Components/Header";
import Footer from "./Components/Footer";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AnimatePresence mode="wait">
          <Header />
          {/* <Transition /> */}
          <motion.div key={router.route} className="h-full w-full">
            {children}
          </motion.div>
          <Footer />
        </AnimatePresence>
      </body>
    </html>
  );
}
