"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { AnimatePresence, motion } from "framer-motion";
import Transition from "./Components/Transition";
import { useRouter } from "next/navigation";
import Header from "./Components/Header";
import Footer from "./Components/Footer";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "SAE 4 INDIA",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  return (
    <html lang="en">
      {/* <Head>
        <link rel="icon" href="SAE4INDIA_logo.ico" type="image/x-icon" />
        <meta name="description" content="SAE 4 INDIA " />
        <title>SAE 4 INDIA</title>
      </Head> */}
      <body className={inter.className}>
        <AnimatePresence mode="popLayout">
          <Header />
          <Transition />
          <motion.div key={router.route} className="h-full w-full">
            {children}
          </motion.div>
          <Footer />
        </AnimatePresence>
      </body>
    </html>
  );
}
